server:
  port: 7070

spring:
  datasource:
    url: jdbc:h2:file:./Desktop/Mini Projects/h2_database/testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp


  #  mail starter smtp configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: #hidden
    password: #hidden
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


